import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { auth, signIn, signOut } from "~/server/auth";
import { ImageUploadButton } from "~/app/_components/uploadthing";
import Link from "next/link";
import { Routes } from "~/consts/routes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export function SignIn({ text = "Sign in" }) {
  return (
    <form
      action={async () => {
        "use server";
        await signIn();
      }}
    >
      <button type="submit">{text}</button>
    </form>
  );
}

function SignOut() {
  return (
    <form
      action={async () => {
        "use server";
        await signOut();
      }}
    >
      <button type="submit">Sign Out</button>
    </form>
  );
}

function UserGreet(name: string | undefined | null) {
  return <span>Hello {name}!</span>;
}

async function TopNav() {
  const session = await auth();
  console.log("session", session);

  return (
    <nav
      className={
        "flex items-center justify-between w-full p-4 text-xl font-semibold border-b"
      }
    >
      <Link href={Routes.HOME}>Gallery</Link>
      {!!session?.user && UserGreet(session.user.name)}
      <div className={"flex"}>
        {!!session?.user && <ImageUploadButton />}
        {!!session?.user ? <SignOut /> : <SignIn />}
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
  modal
}: Readonly<{ children: React.ReactNode, modal: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className={` font-sans flex flex-col gap-4`}>
        <TopNav />
        <TRPCReactProvider>
          {children}
          {modal}
          <div id={"modal-root"} />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
